import { useEffect, useState } from 'react'
import { summitSupabase } from '../lib/summitSupabase'
import SummitPresentationManager from './SummitPresentationManager'

export default function SummitContentManager(){
 const [sessions,setSessions]=useState([]),[selectedId,setSelectedId]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{if(!summitSupabase){setLoading(false);return} summitSupabase.from('sessions').select('id,day_id,sort_order,start_time,title,facilitator,facilitator_bio,facilitator_headshot_url').order('day_id').order('sort_order').then(({data})=>{setSessions(data||[]);setSelectedId(data?.[0]?.id||'');setLoading(false)})},[])
 const session=sessions.find(s=>s.id===selectedId)
 return <div style={{minHeight:'100vh',background:'#f3f6fa',fontFamily:'Inter,system-ui,-apple-system,"Segoe UI",sans-serif',color:'#172337'}}><header style={{background:'#102f56',color:'#fff',padding:'24px 30px'}}><div style={{maxWidth:1100,margin:'auto'}}><div style={{fontSize:10,letterSpacing:'.12em',opacity:.75}}>SUMMIT OF AMERICAN SPACES IN NIGERIA 2026 · COORDINATOR</div><h1 style={{margin:'6px 0',fontSize:30}}>Presentation & Content Manager</h1><p style={{margin:0,fontSize:13,color:'#d9e3ef'}}>Upload presentations and attach resources to individual Summit sessions before the event.</p></div></header><main style={{maxWidth:1100,margin:'20px auto',padding:'0 16px'}}><div style={{background:'#fff',border:'1px solid #dce4ed',borderRadius:14,padding:18}}><label style={{fontSize:11,fontWeight:800,color:'#40536b'}}>SELECT PROGRAMME SESSION</label><select value={selectedId} onChange={e=>setSelectedId(e.target.value)} style={{display:'block',width:'100%',marginTop:7,padding:11,border:'1px solid #ccd6e1',borderRadius:8,fontSize:13}}>{loading&&<option>Loading programme…</option>}{sessions.map(s=><option key={s.id} value={s.id}>{s.day_id.toUpperCase()} · {s.start_time} · {s.title}</option>)}</select></div>{session&&<div style={{marginTop:15}}><SummitPresentationManager session={session}/></div>}<div style={{marginTop:15,padding:14,background:'#fff',border:'1px solid #dce4ed',borderRadius:14,fontSize:11,color:'#63748a',lineHeight:1.6}}><strong>Recommended workflow:</strong> upload the PDF version for live synchronized presentation, then upload the original PPT/PPTX as a downloadable source if required. Maximum file size is 50 MB per file.</div></main></div>
}
